# Generated by Django 5.2.6 on 2025-09-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(help_text='Use URL path (eg: /, /buy-bike/ )', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_external', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_text', models.CharField(default='Drive', max_length=50)),
                ('right_text', models.CharField(default='RP', max_length=50)),
                ('left_color', models.CharField(default='#2b8ecb', max_length=7)),
                ('right_color', models.CharField(default='#ff6b6b', max_length=7)),
                ('shadow', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
