# Generated by Django 5.2.6 on 2025-09-10 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=120)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about/hero/')),
                ('intro_heading', models.CharField(default='About Us', max_length=120)),
                ('intro_paragraph', models.TextField(default="At Drive RP, we're passionate about making cycling accessible and sustainable for everyone...")),
                ('highlight_text', models.CharField(default='Drive RP', max_length=40)),
                ('success_image', models.ImageField(blank=True, null=True, upload_to='about/success/')),
                ('mission_title', models.CharField(default='Our Mission', max_length=120)),
                ('mission_text', models.TextField(default='Our mission is to make cycling more accessible, affordable, and sustainable...')),
                ('mission_overlay_opacity', models.FloatField(default=0.95)),
                ('approach_heading', models.CharField(default='Our Approach', max_length=120)),
                ('approach_paragraph', models.TextField(default='We believe buying or selling a secondhand bike should be simple, safe, and stress-free...')),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='ApproachImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/approach/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Sort order')),
                ('grid_position', models.PositiveSmallIntegerField(default=0, help_text='Grid slot (optional ordering)')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approach_images', to='core.aboutpage')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
