# Generated by Django 5.2.6 on 2025-09-12 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testride'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_heading', models.CharField(default='Buy or Sell Bikes the Smarter Way', max_length=200)),
                ('hero_highlight', models.CharField(blank=True, help_text="Put the exact word/phrase to highlight, e.g. 'Buy or Sell Bikes'", max_length=80)),
                ('hero_paragraph', models.TextField(default='Skip the hassle. Discover verified secondhand bikes at great prices or list your own in minutes. We’re here to help you ride more, spend less, and keep bikes moving — from one happy rider to the next.')),
                ('hero_button_text', models.CharField(default='Buy Now', max_length=40)),
                ('hero_button_url', models.CharField(blank=True, default='#', max_length=255)),
                ('carousel_interval', models.PositiveIntegerField(default=3500, help_text='Milliseconds between image changes')),
            ],
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/hero/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.homepage')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
