# Generated by Django 5.2.6 on 2025-09-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_homepage_heroimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Buying and selling secondhand bikes isn’t just a smart financial decision', max_length=140)),
                ('paragraph', models.TextField(default="— it’s a sustainable one. When you buy a pre-owned bike, you save money while gaining access to a wider variety of models, often already assembled and ready to ride. It's an eco-friendly choice that helps reduce manufacturing waste and supports a circular economy. On the other hand, selling your bike allows you to earn extra cash, declutter your space, and pass on a reliable ride to someone new.")),
                ('button_text', models.CharField(default='Read More', max_length=40)),
                ('button_url', models.CharField(blank=True, default='#', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/feature/')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers show first')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home Feature Section',
                'verbose_name_plural': 'Home Feature Sections',
                'ordering': ('order',),
            },
        ),
    ]
