# Generated by Django 5.2.6 on 2025-09-12 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_homefeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Get the Support You Needs', max_length=160)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='home/support/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('direction', models.CharField(choices=[('down', 'Down (arrow points down)'), ('up', 'Up (arrow points up)')], default='down', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.supportsection')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
