# Generated by Django 5.2.4 on 2025-09-13 02:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_supportsection_supportitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_line_1', models.CharField(blank=True, max_length=120)),
                ('title_line_2', models.CharField(blank=True, max_length=120)),
                ('title_line_3', models.CharField(blank=True, max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('accent_color', models.CharField(default='#0b5fa5', help_text='Hex color (for accents)', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='SellRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=120)),
                ('variant', models.CharField(max_length=120)),
                ('year', models.PositiveIntegerField()),
                ('kms_range', models.CharField(choices=[('Under 5,000', 'Under 5,000'), ('5,000 - 20,000', '5,000 - 20,000'), ('20,000 - 50,000', '20,000 - 50,000'), ('50,000+', '50,000+')], max_length=40)),
                ('owner', models.CharField(choices=[('1st Owner', '1st Owner'), ('2nd Owner', '2nd Owner'), ('3rd+ Owner', '3rd+ Owner')], max_length=30)),
                ('estimated_price', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, help_text='Optional seller name', max_length=120)),
                ('phone', models.CharField(blank=True, help_text='Optional phone', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
