# Generated by Django 5.2.4 on 2025-09-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_banner_sellrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HappyCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='home/')),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SatisfiedCustomerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='home/')),
                ('stat1_icon', models.ImageField(upload_to='home/')),
                ('stat1_number', models.CharField(max_length=50)),
                ('stat1_text', models.CharField(max_length=100)),
                ('stat2_icon', models.ImageField(upload_to='home/')),
                ('stat2_number', models.CharField(max_length=50)),
                ('stat2_text', models.CharField(max_length=100)),
                ('stat3_icon', models.ImageField(upload_to='home/')),
                ('stat3_number', models.CharField(max_length=50)),
                ('stat3_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrustedRidersSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('subtext', models.TextField()),
                ('image', models.ImageField(upload_to='home/')),
            ],
        ),
    ]
